name: voip_softphone
description: PacketDial - Windows SIP softphone (Flutter + Rust FFI)
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.2.0
  package_info_plus: ^9.0.0
  http: ^1.2.1
  window_manager: ^0.5.1
  bitsdojo_window: ^0.1.6
  tray_manager: ^0.5.2
  local_notifier: ^0.1.6
  hotkey_manager: ^0.2.3
  flutter_riverpod: ^2.6.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.5
  uuid: ^4.5.3
  intl: ^0.20.2
  google_fonts: ^8.0.2
  shared_preferences: ^2.2.3
  phone_numbers_parser: ^9.0.20
  just_audio: ^0.10.5
  file_picker: ^10.3.10
  path: ^1.9.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.9
  isar_generator: ^3.1.0+1
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/app_icon.png
    - assets/app_icon.ico
    - assets/sounds/

flutter_launcher_icons:
  android: false
  ios: false
  windows:
    generate: true
    image_path: "assets/app_icon.png"
    icon_size: 256
