# PacketDial Windows Installer Builder
# Creates a professional Windows installer using Inno Setup

param(
    [string]$Version = "1.0.0",
    [string]$OutputDir = "dist",
    [switch]$NoClean
)

$ErrorActionPreference = "Stop"

Write-Host "========================================" -ForegroundColor Cyan
Write-Host "PacketDial Installer Builder" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# Configuration
$AppName = "PacketDial"
$AppPublisher = "PacketDial"
$AppExe = "PacketDial.exe"
$BuildDir = "app_flutter\build\windows\x64\runner\Release"
$InstallerDir = "installer"
$InnoScript = "$InstallerDir\setup.iss"

# Create output directory
if (!(Test-Path $OutputDir)) {
    New-Item -ItemType Directory -Path $OutputDir | Out-Null
}

# Create installer directory
if (!(Test-Path $InstallerDir)) {
    New-Item -ItemType Directory -Path $InstallerDir | Out-Null
}

Write-Host "[1/5] Building Flutter Windows app..." -ForegroundColor Yellow
cd app_flutter
flutter build windows --release
if ($LASTEXITCODE -ne 0) {
    Write-Host "ERROR: Flutter build failed!" -ForegroundColor Red
    exit 1
}
cd ..

Write-Host "[2/5] Copying build files..." -ForegroundColor Yellow
$StagingDir = "$InstallerDir\staging"
if (Test-Path $StagingDir) {
    Remove-Item -Recurse -Force $StagingDir
}
New-Item -ItemType Directory -Path $StagingDir | Out-Null

# Copy Flutter build output
Copy-Item -Path "$BuildDir\*" -Destination $StagingDir -Recurse

# Copy installer icon (if exists)
$IconSource = "assets\installer\icon.ico"
if (Test-Path $IconSource) {
    Copy-Item -Path $IconSource -Destination "$InstallerDir\app_icon.ico"
    Write-Host "  Icon copied: $IconSource" -ForegroundColor Gray
} else {
    Write-Host "  No custom icon found, using default" -ForegroundColor Gray
}

Write-Host "[3/5] Creating Inno Setup script..." -ForegroundColor Yellow

$InnoContent = @"
; Inno Setup Script for PacketDial
; Generated by build_installer.ps1

#define MyAppName "$AppName"
#define MyAppVersion "$Version"
#define MyAppPublisher "$AppPublisher"
#define MyAppExeName "$AppExe"

[Setup]
AppId={{A1B2C3D4-E5F6-7890-ABCD-EF1234567890}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={autopf}\{#MyAppName}
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes
OutputDir=..\$OutputDir
OutputBaseFilename=PacketDial-Setup-$Version
SetupIconFile=compiler:SetupClassicIcon.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern
PrivilegesRequired=admin
ArchitecturesAllowed=x64
ArchitecturesInstallIn64BitMode=x64

; Use custom app icon if available
#if FileExists("app_icon.ico")
SetupIconFile=app_icon.ico
#endif

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "quicklaunchicon"; Description: "{cm:CreateQuickLaunchIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked; OnlyBelowVersion: 6.1; Check: not IsAdminInstallMode

[Files]
Source: "staging\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon
Name: "{userappdata}\Microsoft\Internet Explorer\Quick Launch\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: quicklaunchicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[Code]
function InitializeSetup(): Boolean;
var
  ResultCode: Integer;
begin
  Result := True;
end;
"@

Set-Content -Path $InnoScript -Value $InnoContent

Write-Host "[4/5] Checking for Inno Setup..." -ForegroundColor Yellow

# Check for Inno Setup
$InnoPaths = @(
    "C:\Program Files (x86)\Inno Setup 6\ISCC.exe",
    "C:\Program Files\Inno Setup 6\ISCC.exe",
    "C:\Program Files (x86)\Inno Setup 5\ISCC.exe"
)

$InnoCompiler = $null
foreach ($path in $InnoPaths) {
    if (Test-Path $path) {
        $InnoCompiler = $path
        break
    }
}

if ($InnoCompiler) {
    Write-Host "[5/5] Building installer with Inno Setup..." -ForegroundColor Yellow
    Write-Host "Using: $InnoCompiler" -ForegroundColor Gray
    
    & $InnoCompiler $InnoScript
    
    if ($LASTEXITCODE -eq 0) {
        Write-Host ""
        Write-Host "========================================" -ForegroundColor Green
        Write-Host "Installer created successfully!" -ForegroundColor Green
        Write-Host "========================================" -ForegroundColor Green
        Write-Host ""
        Write-Host "Output: $OutputDir\PacketDial-Setup-$Version.exe" -ForegroundColor Cyan
        Write-Host ""
    } else {
        Write-Host "ERROR: Inno Setup compilation failed!" -ForegroundColor Red
        exit 1
    }
} else {
    Write-Host ""
    Write-Host "WARNING: Inno Setup not found!" -ForegroundColor Yellow
    Write-Host ""
    Write-Host "To create the installer, please install Inno Setup:" -ForegroundColor Yellow
    Write-Host "  https://jrsoftware.org/isdl.php#stable" -ForegroundColor Cyan
    Write-Host ""
    Write-Host "Build files are ready in: $StagingDir" -ForegroundColor Yellow
    Write-Host ""
    
    # Create a simple ZIP as fallback
    Write-Host "Creating ZIP archive as fallback..." -ForegroundColor Yellow
    $ZipPath = "$OutputDir\PacketDial-$Version.zip"
    Compress-Archive -Path "$StagingDir\*" -DestinationPath $ZipPath -Force
    Write-Host "Fallback ZIP created: $ZipPath" -ForegroundColor Cyan
}

# Cleanup
if (!$NoClean -and (Test-Path $StagingDir)) {
    Write-Host ""
    Write-Host "Cleaning up staging directory..." -ForegroundColor Gray
    Remove-Item -Recurse -Force $StagingDir
}

Write-Host ""
Write-Host "Done!" -ForegroundColor Green
